# Generated by Django 3.0.4 on 2020-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=65535)),
                ('type', models.CharField(choices=[('image/bmp', 'Image/Bmp'), ('image/gif', 'Image/Gif'), ('image/jpeg', 'Image/Jpeg'), ('image/tiff', 'Image/Tiff'), ('image/png', 'Image/Png'), ('image/svg+xml', 'Image/Svg+Xml'), ('image/webp', 'Image/Webp')], max_length=20)),
                ('checksum', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'nebula_img',
            },
        ),
    ]
