# Generated by Django 3.0.4 on 2020-04-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgDB', '0002_auto_20200416_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='images',
            new_name='image',
        ),
    ]
