# Generated by Django 3.0.4 on 2020-04-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgDB', '0004_auto_20200417_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
