# Generated by Django 2.2.5 on 2019-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'project_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=45)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('room_name', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('program_type', models.CharField(blank=True, max_length=20, null=True)),
                ('program_order', models.IntegerField(blank=True, null=True)),
                ('has_av', models.IntegerField(blank=True, null=True)),
                ('has_window', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('internal_room_count', models.IntegerField(blank=True, null=True)),
                ('work_unit', models.IntegerField(blank=True, null=True)),
                ('physical_desk_count', models.IntegerField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, max_length=45, null=True)),
                ('group_type', models.CharField(blank=True, max_length=45, null=True)),
                ('upload_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'project_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('room_name', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('outline', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'room_boundary',
                'managed': False,
            },
        ),
    ]
