# Generated by Django 3.0.4 on 2020-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.UUIDField(primary_key=True, serialize=False)),
                ('level_revit_id', models.IntegerField(blank=True, null=True)),
                ('floor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('notes', models.FloatField(blank=True, null=True)),
                ('gsf', models.FloatField(blank=True, null=True)),
                ('usf', models.FloatField(blank=True, null=True)),
                ('rsf', models.FloatField(blank=True, null=True)),
                ('usf_per_desk', models.FloatField(blank=True, null=True)),
                ('deskcount', models.IntegerField(blank=True, null=True)),
                ('average_office_deskcount', models.FloatField(blank=True, null=True)),
                ('geometric_level', models.IntegerField(blank=True, null=True)),
                ('lounge_percent_of_usf', models.FloatField(blank=True, null=True)),
                ('physical_desk_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebula_project_floors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('stargate_id', models.UUIDField()),
                ('pmr_repository_id', models.UUIDField()),
                ('project_name', models.CharField(blank=True, max_length=20, null=True)),
                ('building_name', models.CharField(blank=True, max_length=50, null=True)),
                ('business_line', models.CharField(blank=True, max_length=50, null=True)),
                ('landlord_id', models.UUIDField(blank=True, null=True)),
                ('project_address_point', models.TextField(blank=True, null=True)),
                ('project_address_en', models.CharField(blank=True, max_length=50, null=True)),
                ('project_address_local', models.CharField(blank=True, max_length=50, null=True)),
                ('project_market', models.CharField(blank=True, max_length=50, null=True)),
                ('project_city', models.CharField(blank=True, max_length=50, null=True)),
                ('project_status', models.CharField(blank=True, max_length=50, null=True)),
                ('usf_per_desk', models.FloatField(blank=True, null=True)),
                ('project_id', models.UUIDField(primary_key=True, serialize=False)),
                ('pmr_branch_id', models.UUIDField(blank=True, null=True)),
                ('average_office_desk_count', models.FloatField(blank=True, null=True)),
                ('template_version', models.CharField(blank=True, max_length=10, null=True)),
                ('revit_file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nebula_project_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
        migrations.AlterModelTable(
            name='room',
            table='nebula_project_rooms',
        ),
    ]
